const Intro = () => {
  return (
    <section className="introSection">
        <p className="introSection__paragraph introSection__paragraphOne">
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">J'ai</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">commencé</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">mon</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">chemin</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">dans</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">le</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">monde</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">du</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">dévelpoppement</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">web</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">en</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">autodidacte</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">par</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">pure</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">curiosité.</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">Rapidement,</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">j'ai</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">été</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">fasciné</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">par</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">la</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">puissance</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">de</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">la</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">programmation</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">et</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">j'ai</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">décidé</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">de</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">rejoindre</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">la</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">formation</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">de</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">développeur</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">Front-End</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">d'Open</span>
            <span className ="introSection__paragraph--span introSection__paragraphOne--span">Classrooms.</span>
        </p>
        <p className="introSection__paragraph introSection__paragraphTwo">
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">Parallèlement</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">à</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">cette</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">formation,</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">j'ai</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">exploré</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">d'autres</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">cours</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">et</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">me</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">suis</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">lancé</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">dans</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">divers</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">projets.</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">Cette</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">démarche</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">m'a</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">permis</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">d'élargir</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">mes</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">compétences</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">et</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">d'appréhender</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">le</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">développement</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">web</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">sous</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">des</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">perspectives</span>
            <span className ="introSection__paragraph--span introSection__paragraphTwo--span">variées.</span>
        </p>
        <p className="introSection__paragraph introSection__paragraphThree">
            <span className ="introSection__paragraph--span introSection__paragraphThree--span">Développeur</span>
            <span className ="introSection__paragraph--span introSection__paragraphThree--span">enthousiaste,</span>
            <span className ="introSection__paragraph--span introSection__paragraphThree--span">je</span>
            <span className ="introSection__paragraph--span introSection__paragraphThree--span">fusionne</span>
            <span className ="introSection__paragraph--span introSection__paragraphThree--span">ma</span>
            <span className ="introSection__paragraph--span introSection__paragraphThree--span">passion</span>
            <span className ="introSection__paragraph--span introSection__paragraphThree--span">pour</span>
            <span className ="introSection__paragraph--span introSection__paragraphThree--span">le</span>
            <span className ="introSection__paragraph--span introSection__paragraphThree--span">code</span>
            <span className ="introSection__paragraph--span introSection__paragraphThree--span">avec</span>
            <span className ="introSection__paragraph--span introSection__paragraphThree--span">une</span>
            <span className ="introSection__paragraph--span introSection__paragraphThree--span">expérience</span>
            <span className ="introSection__paragraph--span introSection__paragraphThree--span">entrepreneuriale.</span>
        </p>
        <p className="introSection__paragraph introSection__paragraphFour">
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">Conscient</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">des</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">réalités</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">opérationnelles,</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">je</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">m'efforce</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">de</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">comprendre</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">les</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">besoins</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">du</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">client</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">afin</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">de</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">concevoir</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">des</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">solutions</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">numériques</span>
            <span className ="introSection__paragraph--span introSection__paragraphFour--span">innovantes.</span>
        </p>
        <p className="introSection__paragraph introSection__paragraphFive">
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">Spécialisé</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">dans</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">le</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">développement</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">React,</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">je</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">me</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">consacre</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">à</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">la</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">conception</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">d'applications</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">web</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">à</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">la</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">fois</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">responsives</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">et</span>
            <span className ="introSection__paragraph--span introSection__paragraphFive--span">accessibles.</span>
        </p>
        {/* <p className="introSection__paragraph introSection__paragraphSix">
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">Mon</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">engagement</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">consiste</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">à</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">créer</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">des</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">expériences</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">utilisateur</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">fluides,</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">alignées</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">sur</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">les</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">dernières</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">normes</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">de</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">développement</span>
            <span className ="introSection__paragraph--span introSection__paragraphSix--span">web.</span>
        </p>   */}
    </section>
  )
}

export default Intro
